name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TARGET: FightClubGame

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Release
          - Debug

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: pip install conan

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}} -v --target ${{env.TARGET}}

    - name: Archive Atrifacts
      run: Compress-Archive -Path build/bin/* -DestinationPath ${{env.TARGET}}-${{matrix.configuration}}.zip

    - name: Upload Atrifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TARGET}}-${{matrix.configuration}}
        path: ${{env.TARGET}}-${{matrix.configuration}}.zip



